/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.Color;

/**
 *
 * @author nhaantran
 */
public class InsertBook extends javax.swing.JPanel {

    /**
     * Creates new form InsertBook
     */
    public InsertBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insertbookpane1 = new javax.swing.JPanel();
        lblinsertname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lblinsertname1 = new javax.swing.JLabel();
        txtyear = new javax.swing.JTextField();
        lblinsertname2 = new javax.swing.JLabel();
        txtnational = new javax.swing.JTextField();
        lblinsertname12 = new javax.swing.JLabel();
        txtnumpages = new javax.swing.JTextField();
        lblinsertname13 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        insertbookpane2 = new javax.swing.JPanel();
        lblinsertname7 = new javax.swing.JLabel();
        lblinsertname4 = new javax.swing.JLabel();
        lblinsertname5 = new javax.swing.JLabel();
        lblinsertname6 = new javax.swing.JLabel();
        cbbsupplier = new javax.swing.JComboBox<>();
        cbbbookcover = new javax.swing.JComboBox<>();
        cbbauthor = new javax.swing.JComboBox<>();
        cbbtype = new javax.swing.JComboBox<>();
        lblinsertname11 = new javax.swing.JLabel();
        cbbpublisher = new javax.swing.JComboBox<>();
        insertbookpane3 = new javax.swing.JPanel();
        btnadd = new javax.swing.JButton();
        lblinsertname3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdescription = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        insertbookpane1.setBackground(new java.awt.Color(255, 255, 255));

        lblinsertname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinsertname.setForeground(new java.awt.Color(0, 0, 0));
        lblinsertname.setText("Name:");

        txtname.setForeground(new java.awt.Color(153, 153, 153));
        txtname.setText("Enter Name");
        txtname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnameFocusLost(evt);
            }
        });
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        lblinsertname1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinsertname1.setForeground(new java.awt.Color(0, 0, 0));
        lblinsertname1.setText("Year");

        txtyear.setForeground(new java.awt.Color(153, 153, 153));
        txtyear.setText("Enter Year");
        txtyear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtyearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtyearFocusLost(evt);
            }
        });

        lblinsertname2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinsertname2.setForeground(new java.awt.Color(0, 0, 0));
        lblinsertname2.setText("National:");

        txtnational.setForeground(new java.awt.Color(153, 153, 153));
        txtnational.setText("Enter National");
        txtnational.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnationalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnationalFocusLost(evt);
            }
        });

        lblinsertname12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinsertname12.setForeground(new java.awt.Color(0, 0, 0));
        lblinsertname12.setText("NumPages:");

        txtnumpages.setForeground(new java.awt.Color(153, 153, 153));
        txtnumpages.setText("Enter NumPages");
        txtnumpages.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnumpagesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnumpagesFocusLost(evt);
            }
        });

        lblinsertname13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinsertname13.setForeground(new java.awt.Color(0, 0, 0));
        lblinsertname13.setText("Price:");

        txtprice.setForeground(new java.awt.Color(153, 153, 153));
        txtprice.setText("Enter Price");
        txtprice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpriceFocusLost(evt);
            }
        });

        javax.swing.GroupLayout insertbookpane1Layout = new javax.swing.GroupLayout(insertbookpane1);
        insertbookpane1.setLayout(insertbookpane1Layout);
        insertbookpane1Layout.setHorizontalGroup(
            insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertbookpane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertbookpane1Layout.createSequentialGroup()
                        .addGroup(insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblinsertname, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblinsertname1))
                        .addGap(57, 57, 57)
                        .addGroup(insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtyear)
                            .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertbookpane1Layout.createSequentialGroup()
                        .addGroup(insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblinsertname12)
                            .addComponent(lblinsertname13)
                            .addComponent(lblinsertname2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnational)
                            .addComponent(txtprice)
                            .addComponent(txtnumpages))))
                .addContainerGap())
        );
        insertbookpane1Layout.setVerticalGroup(
            insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertbookpane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinsertname)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinsertname1)
                    .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinsertname2)
                    .addComponent(txtnational, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinsertname12)
                    .addComponent(txtnumpages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(insertbookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinsertname13)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        insertbookpane2.setBackground(new java.awt.Color(255, 255, 255));

        lblinsertname7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinsertname7.setForeground(new java.awt.Color(0, 0, 0));
        lblinsertname7.setText("Supplier:");

        lblinsertname4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinsertname4.setForeground(new java.awt.Color(0, 0, 0));
        lblinsertname4.setText("BookCover:");

        lblinsertname5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinsertname5.setForeground(new java.awt.Color(0, 0, 0));
        lblinsertname5.setText("Author:");

        lblinsertname6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinsertname6.setForeground(new java.awt.Color(0, 0, 0));
        lblinsertname6.setText("Type:");

        cbbsupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbbookcover.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbauthor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbbtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblinsertname11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinsertname11.setForeground(new java.awt.Color(0, 0, 0));
        lblinsertname11.setText("Publisher:");

        cbbpublisher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout insertbookpane2Layout = new javax.swing.GroupLayout(insertbookpane2);
        insertbookpane2.setLayout(insertbookpane2Layout);
        insertbookpane2Layout.setHorizontalGroup(
            insertbookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertbookpane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertbookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertbookpane2Layout.createSequentialGroup()
                        .addComponent(lblinsertname7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(insertbookpane2Layout.createSequentialGroup()
                        .addComponent(lblinsertname6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(insertbookpane2Layout.createSequentialGroup()
                        .addComponent(lblinsertname4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(cbbbookcover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(insertbookpane2Layout.createSequentialGroup()
                        .addComponent(lblinsertname5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbauthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(insertbookpane2Layout.createSequentialGroup()
                        .addComponent(lblinsertname11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbpublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        insertbookpane2Layout.setVerticalGroup(
            insertbookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertbookpane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertbookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblinsertname7)
                    .addComponent(cbbsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(insertbookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblinsertname4)
                    .addComponent(cbbbookcover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(insertbookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblinsertname5)
                    .addComponent(cbbauthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(insertbookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblinsertname6)
                    .addComponent(cbbtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(insertbookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblinsertname11)
                    .addComponent(cbbpublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        insertbookpane3.setBackground(new java.awt.Color(255, 255, 255));

        btnadd.setBackground(new java.awt.Color(0, 153, 255));
        btnadd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 255, 255));
        btnadd.setText("Add Book");
        btnadd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblinsertname3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblinsertname3.setForeground(new java.awt.Color(0, 0, 0));
        lblinsertname3.setText("Description");

        txtdescription.setColumns(20);
        txtdescription.setLineWrap(true);
        txtdescription.setRows(5);
        jScrollPane1.setViewportView(txtdescription);

        javax.swing.GroupLayout insertbookpane3Layout = new javax.swing.GroupLayout(insertbookpane3);
        insertbookpane3.setLayout(insertbookpane3Layout);
        insertbookpane3Layout.setHorizontalGroup(
            insertbookpane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertbookpane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblinsertname3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(insertbookpane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addContainerGap())
        );
        insertbookpane3Layout.setVerticalGroup(
            insertbookpane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertbookpane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertbookpane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblinsertname3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnadd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(insertbookpane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(insertbookpane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(insertbookpane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insertbookpane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertbookpane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(insertbookpane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusGained
        // TODO add your handling code here:
        if(txtname.getText().equals("Enter Name")){
            txtname.setText("");
            txtname.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtnameFocusGained

    private void txtnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusLost
        // TODO add your handling code here:
        if(txtname.getText().equals("")){
            txtname.setText("Enter Name");
            txtname.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtnameFocusLost

    private void txtyearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtyearFocusGained
        // TODO add your handling code here:
        if(txtyear.getText().equals("Enter Year")){
            txtyear.setText("");
            txtyear.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtyearFocusGained

    private void txtyearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtyearFocusLost
        // TODO add your handling code here:
        if(txtyear.getText().equals("")){
            txtyear.setText("Enter Year");
            txtyear.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtyearFocusLost

    private void txtnationalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnationalFocusGained
        // TODO add your handling code here:
        if(txtnational.getText().equals("Enter National")){
            txtnational.setText("");
            txtnational.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtnationalFocusGained

    private void txtnationalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnationalFocusLost
        // TODO add your handling code here:
        if(txtnational.getText().equals("")){
            txtnational.setText("Enter National");
            txtnational.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtnationalFocusLost

    private void txtnumpagesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumpagesFocusGained
        // TODO add your handling code here:
        if(txtnumpages.getText().equals("Enter NumPages")){
            txtnumpages.setText("");
            txtnumpages.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtnumpagesFocusGained

    private void txtnumpagesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumpagesFocusLost
        // TODO add your handling code here:
        if(txtnumpages.getText().equals("")){
            txtnumpages.setText("Enter NumPages");
            txtnumpages.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtnumpagesFocusLost

    private void txtpriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpriceFocusGained
        // TODO add your handling code here:
        if(txtprice.getText().equals("Enter Price")){
            txtprice.setText("");
            txtprice.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtpriceFocusGained

    private void txtpriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpriceFocusLost
        // TODO add your handling code here:
        if(txtprice.getText().equals("")){
            txtprice.setText("Enter Price");
            txtprice.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtpriceFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JComboBox<String> cbbauthor;
    private javax.swing.JComboBox<String> cbbbookcover;
    private javax.swing.JComboBox<String> cbbpublisher;
    private javax.swing.JComboBox<String> cbbsupplier;
    private javax.swing.JComboBox<String> cbbtype;
    private javax.swing.JPanel insertbookpane1;
    private javax.swing.JPanel insertbookpane2;
    private javax.swing.JPanel insertbookpane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblinsertname;
    private javax.swing.JLabel lblinsertname1;
    private javax.swing.JLabel lblinsertname11;
    private javax.swing.JLabel lblinsertname12;
    private javax.swing.JLabel lblinsertname13;
    private javax.swing.JLabel lblinsertname2;
    private javax.swing.JLabel lblinsertname3;
    private javax.swing.JLabel lblinsertname4;
    private javax.swing.JLabel lblinsertname5;
    private javax.swing.JLabel lblinsertname6;
    private javax.swing.JLabel lblinsertname7;
    private javax.swing.JTextArea txtdescription;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnational;
    private javax.swing.JTextField txtnumpages;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtyear;
    // End of variables declaration//GEN-END:variables
}
