/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.Color;

/**
 *
 * @author nhaantran
 */
public class UpdateBook extends javax.swing.JPanel {

    /**
     * Creates new form UpdateBook
     */
    public UpdateBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updatebookpane1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rdbtnname = new javax.swing.JRadioButton();
        rdbtnnational = new javax.swing.JRadioButton();
        rdbtnyear = new javax.swing.JRadioButton();
        rdbtnnumpages = new javax.swing.JRadioButton();
        rdbtnprice = new javax.swing.JRadioButton();
        txtid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtnational = new javax.swing.JTextField();
        txtyear = new javax.swing.JTextField();
        txtnumpages = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        updatebookpane2 = new javax.swing.JPanel();
        rdbtnpublisher = new javax.swing.JRadioButton();
        rdbtnsupplier = new javax.swing.JRadioButton();
        rdbtnauthor = new javax.swing.JRadioButton();
        rdbtnbookcover = new javax.swing.JRadioButton();
        rdbtntype = new javax.swing.JRadioButton();
        cbbpublisher = new javax.swing.JComboBox<>();
        cbbsupplier = new javax.swing.JComboBox<>();
        cbbauthor = new javax.swing.JComboBox<>();
        cbbbookcover = new javax.swing.JComboBox<>();
        cbbtype = new javax.swing.JComboBox<>();
        updatebookpane3 = new javax.swing.JPanel();
        rdbtndescription = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdescription = new javax.swing.JTextArea();
        btnupdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        updatebookpane1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Input ID:");

        rdbtnname.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnname.setText("Name");
        rdbtnname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnnameActionPerformed(evt);
            }
        });

        rdbtnnational.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnnational.setText("National");
        rdbtnnational.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnnationalActionPerformed(evt);
            }
        });

        rdbtnyear.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnyear.setText("Year");
        rdbtnyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnyearActionPerformed(evt);
            }
        });

        rdbtnnumpages.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnnumpages.setText("NumPages");
        rdbtnnumpages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnnumpagesActionPerformed(evt);
            }
        });

        rdbtnprice.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnprice.setText("Price");
        rdbtnprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnpriceActionPerformed(evt);
            }
        });

        txtid.setForeground(new java.awt.Color(153, 153, 153));
        txtid.setText("Enter ID");
        txtid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtidFocusLost(evt);
            }
        });

        txtname.setForeground(new java.awt.Color(153, 153, 153));
        txtname.setText("Enter Name");
        txtname.setEnabled(false);
        txtname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnameFocusLost(evt);
            }
        });

        txtnational.setForeground(new java.awt.Color(153, 153, 153));
        txtnational.setText("Enter National");
        txtnational.setEnabled(false);
        txtnational.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnationalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnationalFocusLost(evt);
            }
        });

        txtyear.setForeground(new java.awt.Color(153, 153, 153));
        txtyear.setText("Enter Year");
        txtyear.setEnabled(false);
        txtyear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtyearFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtyearFocusLost(evt);
            }
        });

        txtnumpages.setForeground(new java.awt.Color(153, 153, 153));
        txtnumpages.setText("Enter NumPages");
        txtnumpages.setEnabled(false);
        txtnumpages.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnumpagesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnumpagesFocusLost(evt);
            }
        });

        txtprice.setForeground(new java.awt.Color(153, 153, 153));
        txtprice.setText("Enter Price");
        txtprice.setEnabled(false);
        txtprice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpriceFocusLost(evt);
            }
        });

        javax.swing.GroupLayout updatebookpane1Layout = new javax.swing.GroupLayout(updatebookpane1);
        updatebookpane1.setLayout(updatebookpane1Layout);
        updatebookpane1Layout.setHorizontalGroup(
            updatebookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatebookpane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatebookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnnumpages)
                    .addComponent(rdbtnprice)
                    .addComponent(rdbtnyear)
                    .addComponent(rdbtnnational)
                    .addComponent(rdbtnname)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(updatebookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtid)
                    .addComponent(txtname)
                    .addComponent(txtnational)
                    .addComponent(txtyear)
                    .addComponent(txtprice)
                    .addComponent(txtnumpages))
                .addContainerGap())
        );
        updatebookpane1Layout.setVerticalGroup(
            updatebookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatebookpane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatebookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatebookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnname)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatebookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnnational)
                    .addComponent(txtnational, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatebookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnyear)
                    .addComponent(txtyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatebookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnnumpages)
                    .addComponent(txtnumpages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatebookpane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnprice)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        updatebookpane2.setBackground(new java.awt.Color(255, 255, 255));

        rdbtnpublisher.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnpublisher.setText("Publisher");
        rdbtnpublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnpublisherActionPerformed(evt);
            }
        });

        rdbtnsupplier.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnsupplier.setText("Supplier");
        rdbtnsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnsupplierActionPerformed(evt);
            }
        });

        rdbtnauthor.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnauthor.setText("Author");
        rdbtnauthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnauthorActionPerformed(evt);
            }
        });

        rdbtnbookcover.setForeground(new java.awt.Color(0, 0, 0));
        rdbtnbookcover.setText("BookCover");
        rdbtnbookcover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnbookcoverActionPerformed(evt);
            }
        });

        rdbtntype.setForeground(new java.awt.Color(0, 0, 0));
        rdbtntype.setText("Type");
        rdbtntype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtntypeActionPerformed(evt);
            }
        });

        cbbpublisher.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbpublisher.setEnabled(false);

        cbbsupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbsupplier.setEnabled(false);

        cbbauthor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbauthor.setEnabled(false);

        cbbbookcover.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbbookcover.setEnabled(false);

        cbbtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbtype.setEnabled(false);

        javax.swing.GroupLayout updatebookpane2Layout = new javax.swing.GroupLayout(updatebookpane2);
        updatebookpane2.setLayout(updatebookpane2Layout);
        updatebookpane2Layout.setHorizontalGroup(
            updatebookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatebookpane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatebookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatebookpane2Layout.createSequentialGroup()
                        .addComponent(rdbtnpublisher)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbpublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(updatebookpane2Layout.createSequentialGroup()
                        .addComponent(rdbtntype)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(updatebookpane2Layout.createSequentialGroup()
                        .addComponent(rdbtnsupplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(updatebookpane2Layout.createSequentialGroup()
                        .addComponent(rdbtnauthor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbbauthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(updatebookpane2Layout.createSequentialGroup()
                        .addComponent(rdbtnbookcover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(cbbbookcover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        updatebookpane2Layout.setVerticalGroup(
            updatebookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatebookpane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatebookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnpublisher)
                    .addComponent(cbbpublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatebookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnsupplier)
                    .addComponent(cbbsupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatebookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnauthor)
                    .addComponent(cbbauthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatebookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtnbookcover)
                    .addComponent(cbbbookcover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updatebookpane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbtntype)
                    .addComponent(cbbtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        updatebookpane3.setBackground(new java.awt.Color(255, 255, 255));

        rdbtndescription.setForeground(new java.awt.Color(0, 0, 0));
        rdbtndescription.setText("Description");
        rdbtndescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtndescriptionActionPerformed(evt);
            }
        });

        txtdescription.setColumns(20);
        txtdescription.setLineWrap(true);
        txtdescription.setRows(5);
        txtdescription.setEnabled(false);
        jScrollPane1.setViewportView(txtdescription);

        btnupdate.setBackground(new java.awt.Color(0, 153, 255));
        btnupdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("Update Book");
        btnupdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout updatebookpane3Layout = new javax.swing.GroupLayout(updatebookpane3);
        updatebookpane3.setLayout(updatebookpane3Layout);
        updatebookpane3Layout.setHorizontalGroup(
            updatebookpane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatebookpane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatebookpane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatebookpane3Layout.createSequentialGroup()
                        .addComponent(rdbtndescription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatebookpane3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        updatebookpane3Layout.setVerticalGroup(
            updatebookpane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatebookpane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatebookpane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbtndescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnupdate)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updatebookpane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(updatebookpane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(updatebookpane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updatebookpane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatebookpane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatebookpane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidFocusGained
        // TODO add your handling code here:
        if (txtid.getText().equals("Enter ID")) {
            txtid.setText("");
            txtid.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtidFocusGained

    private void txtidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidFocusLost
        // TODO add your handling code here:
        if (txtid.getText().equals("")) {
            txtid.setText("Enter ID");
            txtid.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtidFocusLost

    private void txtnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusGained
        // TODO add your handling code here:
        if (txtname.getText().equals("Enter Name")) {
            txtname.setText("");
            txtname.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtnameFocusGained

    private void txtnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusLost
        // TODO add your handling code here:
        if (txtname.getText().equals("")) {
            txtname.setText("Enter Name");
            txtname.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtnameFocusLost

    private void txtnationalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnationalFocusGained
        // TODO add your handling code here:
        if (txtnational.getText().equals("Enter National")) {
            txtnational.setText("");
            txtnational.setForeground(new Color(153, 153, 153));
        }

    }//GEN-LAST:event_txtnationalFocusGained

    private void txtnationalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnationalFocusLost
        // TODO add your handling code here:
        if (txtnational.getText().equals("")) {
            txtnational.setText("Enter National");
            txtnational.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtnationalFocusLost

    private void txtyearFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtyearFocusGained
        // TODO add your handling code here:
        if (txtyear.getText().equals("Enter Year")) {
            txtyear.setText("");
            txtyear.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtyearFocusGained

    private void txtyearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtyearFocusLost
        // TODO add your handling code here:
        if (txtyear.getText().equals("")) {
            txtyear.setText("Enter Year");
            txtyear.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtyearFocusLost

    private void txtnumpagesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumpagesFocusGained
        // TODO add your handling code here:
        if (txtnumpages.getText().equals("Enter NumPages")) {
            txtnumpages.setText("");
            txtnumpages.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtnumpagesFocusGained

    private void txtnumpagesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnumpagesFocusLost
        // TODO add your handling code here:
        if (txtnumpages.getText().equals("")) {
            txtnumpages.setText("Enter NumPages");
            txtnumpages.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtnumpagesFocusLost

    private void txtpriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpriceFocusGained
        // TODO add your handling code here:
        if (txtprice.getText().equals("Enter Price")) {
            txtprice.setText("");
            txtprice.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtpriceFocusGained

    private void txtpriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpriceFocusLost
        // TODO add your handling code here:
        if (txtprice.getText().equals("")) {
            txtprice.setText("Enter Price");
            txtprice.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtpriceFocusLost

    private void rdbtnnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnnameActionPerformed
        // TODO add your handling code here:
        if(txtname.isEnabled()){
            txtname.setEnabled(false);
        } else{
            txtname.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtnnameActionPerformed

    private void rdbtnnationalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnnationalActionPerformed
        // TODO add your handling code here:
        if(txtnational.isEnabled()){
            txtnational.setEnabled(false);
        } else{
            txtnational.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtnnationalActionPerformed

    private void rdbtnyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnyearActionPerformed
        // TODO add your handling code here:
        if(txtyear.isEnabled()){
            txtyear.setEnabled(false);
        } else{
            txtyear.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtnyearActionPerformed

    private void rdbtnnumpagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnnumpagesActionPerformed
        // TODO add your handling code here:
        if(txtnumpages.isEnabled()){
            txtnumpages.setEnabled(false);
        } else{
            txtnumpages.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtnnumpagesActionPerformed

    private void rdbtnpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnpriceActionPerformed
        // TODO add your handling code here:
        if(txtprice.isEnabled()){
            txtprice.setEnabled(false);
        } else{
            txtprice.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtnpriceActionPerformed

    private void rdbtnpublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnpublisherActionPerformed
        // TODO add your handling code here:
        if(cbbpublisher.isEnabled()){
            cbbpublisher.setEnabled(false);
        } else{
            cbbpublisher.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtnpublisherActionPerformed

    private void rdbtnsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnsupplierActionPerformed
        // TODO add your handling code here:
        if(cbbsupplier.isEnabled()){
            cbbsupplier.setEnabled(false);
        } else{
            cbbsupplier.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtnsupplierActionPerformed

    private void rdbtnauthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnauthorActionPerformed
        // TODO add your handling code here:
        if(cbbauthor.isEnabled()){
            cbbauthor.setEnabled(false);
        } else{
            cbbauthor.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtnauthorActionPerformed

    private void rdbtnbookcoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnbookcoverActionPerformed
        // TODO add your handling code here:
        if(cbbbookcover.isEnabled()){
            cbbbookcover.setEnabled(false);
        } else{
            cbbbookcover.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtnbookcoverActionPerformed

    private void rdbtntypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtntypeActionPerformed
        // TODO add your handling code here:
        if(cbbtype.isEnabled()){
            cbbtype.setEnabled(false);
        } else{
            cbbtype.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtntypeActionPerformed

    private void rdbtndescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtndescriptionActionPerformed
        // TODO add your handling code here:
        if(txtdescription.isEnabled()){
            txtdescription.setEnabled(false);
        } else{
            txtdescription.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtndescriptionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cbbauthor;
    private javax.swing.JComboBox<String> cbbbookcover;
    private javax.swing.JComboBox<String> cbbpublisher;
    private javax.swing.JComboBox<String> cbbsupplier;
    private javax.swing.JComboBox<String> cbbtype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbtnauthor;
    private javax.swing.JRadioButton rdbtnbookcover;
    private javax.swing.JRadioButton rdbtndescription;
    private javax.swing.JRadioButton rdbtnname;
    private javax.swing.JRadioButton rdbtnnational;
    private javax.swing.JRadioButton rdbtnnumpages;
    private javax.swing.JRadioButton rdbtnprice;
    private javax.swing.JRadioButton rdbtnpublisher;
    private javax.swing.JRadioButton rdbtnsupplier;
    private javax.swing.JRadioButton rdbtntype;
    private javax.swing.JRadioButton rdbtnyear;
    private javax.swing.JTextArea txtdescription;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnational;
    private javax.swing.JTextField txtnumpages;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtyear;
    private javax.swing.JPanel updatebookpane1;
    private javax.swing.JPanel updatebookpane2;
    private javax.swing.JPanel updatebookpane3;
    // End of variables declaration//GEN-END:variables
}
